### ISSUE TITLE
aws-cdk版本冲突的问题

### ISSUE THREAD

**Issue by Hedaqing** [wttat/af2-batch-cdk#1]
文件af2-batch-cdk/requirements.txt中没有指定aws cdk的版本号，在我的环境中执行 `pip3 install -r requirements.txt --no-cache-dir`  时，下载的版本默认是1.139.0，和af2-batch-cdk/af2_batch_cdk/af2_batch_cdk.egg-info/requires.txt中版本号1.121.0冲突。在requirements.txt文件中指定各组件的版本号为1.121.0后，冲突解决了。

暂时不清楚为什么requirements.txt中不指定版本号时会默认下载1.139.0。

**Comment by Hedaqing** [comment]
重新下载代码库后，再次运行`pip3 install -r requirements.txt`，这次的aws cdk组件版本默认是1.121.0，没有复现出1.139.0的问题。看到在setup.py中指定了"aws-cdk.core==1.121.0"

**Comment by wttat** [comment]
我回来检查下，目前在更新af2的新feature。

**Comment by wttat** [comment]
问题已修复
