### ISSUE TITLE
I want to deploy this solution #12

### ISSUE THREAD

**Issue by wpr7280** [wttat/af2-batch-cdk#13]
AWS account ID: 008971646414
Region: ap-northeast-1

I got this error: 

+ aws s3 cp s3://alphafold2/prod/datasets/dataset5.tar.gz ./ --request-payer --region ap-northeast-1 |  
+ fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden |

**Comment by wpr7280** [comment]
@wttat

**Comment by wttat** [comment]
added
